### ISSUE TITLE
Parameter Defaulting Doesn't Highlight Correctly

### ISSUE THREAD

**Issue by stevekuznetsov** [jfcherng/Sublime-ShellScriptImproved#26]
```
$ /usr/local/sublime_text_3/sublime_text --version
Sublime Text Build 3126
```

Installed this package today. Added `"color_scheme": "Packages/ShellScriptImproved/color_schemes/dark.tmTheme"` to my `~/.config/sublime-text-3/Packages/User/Shell-Unix-Generic.sublime-settings`.

On [`hack/test-go.sh`](https://github.com/openshift/origin/blob/master/hack/test-go.sh#L70-L79) I am seeing this:
![defult](https://cloud.githubusercontent.com/assets/7328370/19189633/0b8733e0-8c67-11e6-8c25-fc3eedffdc90.png)

I would have expected the default values to behave differently.

**Comment by stevekuznetsov** [comment]
Toggling colors and such (I prefer my theme, things like `#f92672` for variables) when I set the `<string>Shell - variable</string>` scope color, I see the default values toggle as well, so I guess they're getting caught by one of those identifiers.

**Comment by jfcherng** [comment]
![image](https://cloud.githubusercontent.com/assets/6594915/19191518/676cd1ce-8cd5-11e6-95a4-e05933fd1721.png)

This is what I see in my ST. Could you make sure that the file is parsed with `ShellScript Improved` rather than `Shell Script (Bash)` on the bottom right corner of your ST? Something that ST has cached may be involved in this issue.

**Comment by stevekuznetsov** [comment]
Yes, some windows took more than one open/close cycle to being using the improved parser.. weird. Sorry about this.
